apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  labels:
    app: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard