apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starthack-api-ingress-prod
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls-secret-prod
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1"
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.port }}