apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: starthack-api-test-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: {{ .Values.port }}