apiVersion: v1
kind: Service
metadata:
  name: "app-service"
  labels:
    app: starthack
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: starthack