namespace: starthack-test
env: test
name: starthack-api
replicaCount: 1
image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com/starthack-test/api:ae64f5f86a1e274e0b44345ac53087d2ff1aec21
cpus: 0
port: 8000

awsSecretName: aws-secret-test
clusterIssuer: letsencrypt-test
domain: helvetai-test.dataplumbers.ch

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 50