namespace: starthack-test
env: test
name: starthack-api
replicaCount: 1
image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com/starthack-test/api:d73b98bc67bf0d30f3fff967e9c00e2ef0210ed8
cpus: 0
port: 8000

awsSecretName: aws-secret-test
clusterIssuer: letsencrypt-test
domain: helvetai-test.dataplumbers.ch

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 50