namespace: starthack-prod
env: prod
name: starthack-api
replicaCount: 1
image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com/starthack-prod/api:0.3.0
cpus: 0
port: 8000

awsSecretName: aws-secret-prod
clusterIssuer: letsencrypt-prod
domain: helvetai.dataplumbers.ch

autoscaling:
  minReplicas: 2
  maxReplicas: 10
  averageUtilization: 50