namespace: starthack-test
env: test
name: starthack-api
replicaCount: 1
image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com/starthack-test/api:62e8257879c6113da5290ff1ca7278153bbd7283
cpus: 0
port: 8000

awsSecretName: aws-secret-test
clusterIssuer: letsencrypt-test
domain: helvetai-test.dataplumbers.ch

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 50